env:
  node: true
extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/recommended'
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 12
  sourceType: module
  project:
    - 'tsconfig.json'
plugins:
  - '@typescript-eslint'
rules:
  '@typescript-eslint/no-explicit-any': 0
  '@typescript-eslint/explicit-module-boundary-types': 0
  '@typescript-eslint/ban-ts-comment': 0
  '@typescript-eslint/switch-exhaustiveness-check': 1
  '@typescript-eslint/no-non-null-assertion': 0
  no-invalid-regexp: warn
  no-unreachable: warn
  no-eval: warn
  vars-on-top: warn
  '@typescript-eslint/no-unused-vars':
    - warn
    - args: none
  indent:
    - warn
    - 2
    - SwitchCase: 1
  quotes:
    - warn
    - single
  semi:
    - warn
    - always
    - omitLastInOneLineBlock: true
  no-var: error
  prefer-const: warn
  prefer-template: error
  no-prototype-builtins: 0
  no-fallthrough: 0
  max-len: ['warn', 100, 2, { 'ignoreComments': true, 'ignoreStrings': true }]
  sort-imports:
    - warn
    - ignoreDeclarationSort: true
