SpecVersion = "1.2.0"
LatestCompileDate = "Tue Aug 10 2021"

[CompilerVersion]
CheckSum = "e669fc9629948fa4727b66acee4015f7"
CompiledDate = "Tue Aug 10 2021"

[ProgramInfo."b.br"]
signature = "cd2493a7bb32702bf7268bc32d586b46"
LatestCompileDate = "Tue Aug 10 2021"

[ProgramInfo."c.br"]
signature = "f6d2222ee359676b4cec2a013d69a3c5"
LatestCompileDate = "Tue Aug 10 2021"
