SpecVersion = "1.2.0"
LatestCompileDate = "Mon Aug 16 2021"

[CompilerVersion]
CheckSum = "000c2c162e9f6e57a1841fd31a52e6c0"
CompiledDate = "Mon Aug 16 2021"

[ProgramInfo."b.br"]
signature = "cd2493a7bb32702bf7268bc32d586b46"
LatestCompileDate = "Mon Aug 16 2021"

[ProgramInfo."c.br"]
signature = "f6d2222ee359676b4cec2a013d69a3c5"
LatestCompileDate = "Mon Aug 16 2021"
