SpecVersion = "1.2.0"
LatestCompileDate = "Sun Aug 22 2021"

[CompilerVersion]
CheckSum = "059c43766fd970388b829de84042d9ed"
CompiledDate = "Sun Aug 22 2021"

[ProgramInfo."b.br"]
signature = "cd2493a7bb32702bf7268bc32d586b46"
LatestCompileDate = "Sun Aug 22 2021"

[ProgramInfo."c.br"]
signature = "f6d2222ee359676b4cec2a013d69a3c5"
LatestCompileDate = "Sun Aug 22 2021"
