SpecVersion = "1.1.0"
LatestCompileDate = "Thu Jul 29 2021"

[ProgramInfo."c.br"]
signature = "f6d2222ee359676b4cec2a013d69a3c5"
LatestCompileDate = "Thu Jul 29 2021"

[ProgramInfo."b.br"]
signature = "d2d38e3eb39dbf8c2eb18e3e665d359d"
LatestCompileDate = "Thu Jul 29 2021"
