SpecVersion = "1.1.0"
LatestCompileDate = "Tue Aug 03 2021"

[ProgramInfo."c.br"]
signature = "f6d2222ee359676b4cec2a013d69a3c5"
LatestCompileDate = "Tue Aug 03 2021"

[ProgramInfo."b.br"]
signature = "cdec852d6306780904c1e2f5a6c4d5a5"
LatestCompileDate = "Tue Aug 03 2021"
