SpecVersion = "1.2.0"
LatestCompileDate = "Sat Aug 07 2021"

[CompilerVersion]
CheckSum = "1132c037839c51ba263f00915fa54e2d"
CompiledDate = "Sat Aug 07 2021"

[ProgramInfo."b.br"]
signature = "cd2493a7bb32702bf7268bc32d586b46"
LatestCompileDate = "Sat Aug 07 2021"

[ProgramInfo."c.br"]
signature = "f6d2222ee359676b4cec2a013d69a3c5"
LatestCompileDate = "Sat Aug 07 2021"
