SpecVersion = "1.2.0"
LatestCompileDate = "Tue Aug 10 2021"

[CompilerVersion]
CheckSum = "4363b3c0662ecee2b857b3cd5146dc48"
CompiledDate = "Tue Aug 10 2021"

[ProgramInfo."b.br"]
signature = "cd2493a7bb32702bf7268bc32d586b46"
LatestCompileDate = "Tue Aug 10 2021"

[ProgramInfo."c.br"]
signature = "f6d2222ee359676b4cec2a013d69a3c5"
LatestCompileDate = "Tue Aug 10 2021"
