SpecVersion = "1.2.0"
LatestCompileDate = "Mon Aug 16 2021"

[CompilerVersion]
CheckSum = "18a5a94404d8ab989501860307d55e9c"
CompiledDate = "Mon Aug 16 2021"

[ProgramInfo."b.br"]
signature = "cd2493a7bb32702bf7268bc32d586b46"
LatestCompileDate = "Mon Aug 16 2021"

[ProgramInfo."c.br"]
signature = "f6d2222ee359676b4cec2a013d69a3c5"
LatestCompileDate = "Mon Aug 16 2021"
