SpecVersion = "1.2.0"
LatestCompileDate = ""

[CompilerVersion]
CheckSum = "af3150a06fa53ed50416cdfe5498bdba"
CompiledDate = "Sat Dec 11 2021"

[ProgramInfo."code.br"]
signature = "8737a669b7a97b807a8d4e8034d86a7a"
LatestCompileDate = "Sat Dec 11 2021"
