SpecVersion = "1.2.0"
LatestCompileDate = ""

[CompilerVersion]
CheckSum = "0103dadec4045a357b487e87083fe01b"
CompiledDate = "Sun Nov 28 2021"

[ProgramInfo."code.br"]
signature = "fb642c7ea72bde23a7c0b3ca3ba4a70e"
LatestCompileDate = "Sun Nov 28 2021"
