SpecVersion = "1.2.0"
LatestCompileDate = ""

[CompilerVersion]
CheckSum = "e734afc6a0ed3d43fb55f330fd72c064"
CompiledDate = "Sat Oct 02 2021"

[ProgramInfo."code.br"]
signature = "6936fcf23a58dfb1e1c27cd0f5901723"
LatestCompileDate = "Sat Oct 02 2021"
