SpecVersion = "1.2.0"
LatestCompileDate = ""

[CompilerVersion]
CheckSum = "852ec514da4bb1865eead559257fa77f"
CompiledDate = "Sat Dec 11 2021"

[ProgramInfo."code.br"]
signature = "0647f47fe666e47a41a4c75ff96cb7b0"
LatestCompileDate = "Sat Dec 11 2021"
